---
# tasks file for roles/samba
- name: Install Samba server
  package:
      name: samba
      state: present

- name: Create directory for share
  file:
    path: "{{ share_path }}"
    mode: "0777"
    state: directory
    recurse: true

- name: Copy Samba configuration
  template:
    src: smb.conf
    dest: /etc/samba/smb.conf
  notify:
    - Restart Samba

- name: Start samba
  service:
    name: smbd
    state: started
    enabled: true
