---
# tasks file for roles/samba
- name: Install Samba server
  package:
      name: samba
      state: present

- name: Copy Samba configuration
  template:
    src: smb.conf
    dest: /etc/samba/smb.conf

- name: Start samba
  systemd_service:
    name: smbd
    state: started
    enabled: true
  notify:
    - Restart Samba

