# Tasks file for roles/ghosts-linux
---
- name: Install .NET Runtime and deploy project
  hosts: linux_workstations
  become: true
  vars:
    dotnet_version: "8.0"
    project_path: "/home/ansibleuser/my_dotnet_project"
    runtime_url: "https://dotnet.microsoft.com/en-us/download/dotnet/{{ dotnet_version }}"
    dotnet_install_script: "https://dot.net/v1/dotnet-install.sh"

  tasks:
    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
      when: ansible_os_family == "Debian"

    - name: Download dotnet install script
      get_url:
        url: "{{ dotnet_install_script }}"
        dest: /tmp/dotnet-install.sh
        mode: '0755'

    - name: Install .NET 8.0 Runtime
      shell: |
        /tmp/dotnet-install.sh --runtime dotnet --version {{ dotnet_version }} --install-dir /usr/share/dotnet
      args:
        creates: "/usr/share/dotnet/dotnet"

    - name: Add dotnet to PATH
      lineinfile:
        path: /etc/profile.d/dotnet.sh
        create: yes
        line: 'export PATH=$PATH:/usr/share/dotnet'

    - name: Build .NET project
      shell: |
        source /etc/profile.d/dotnet.sh
        /usr/share/dotnet/dotnet build {{ project_path }} --configuration Release
      args:
        chdir: "{{ project_path }}"

- name: Copy build folder to target
  hosts: target_machine
  become: true
  vars:
    project_path: "/home/ansibleuser/my_dotnet_project"
    destination_path: "/opt/myapp/bin"

  tasks:
    - name: Copy bin folder from controller to target
      copy:
        src: "{{ project_path }}/bin/"
        dest: "{{ destination_path }}/"
        mode: '0755'
