# Tasks file for roles/ghosts-linux
---

# - name: Build the Ghosts Linux client
#   hosts: localhost
#   vars:
#     ghosts_client_path: "../../src/ghosts.client.linux/"
#   tasks:
#     - name: Install dependencies
#       shell: |
#         dotnet restore {{ ghosts_client_path }}
#     - name: Build client
#         dotnet build {{ ghosts_client_path }} --configuration Release;

- name: Setup Ghosts client
  hosts: linux_workstations
  become: true
  vars:
    client_path: "../resources/ghosts-linux.tar.gz"
    dotnet_path: "../resources/aspnetcore-runtime-8.0.14-linux-x64.tar.gz"
    client_target_path: "/root/ghosts"
    dotnet_target_path: "/root/dotnet"
    dotnet_sh_path: "/etc/profile.d/dotnet.sh"
  tasks:
  - name: Create folder for client
    file:
      path: "{{ client_target_path }}"
      state: directory
  - name: Copy the client
    unarchive:
      src: "{{ client_path }}"
      dest: "{{ client_target_path }}"
      creates: "{{ client_target_path }}/config"
  - name: Create folder for Dotnet
    file:
      path: "{{ dotnet_target_path }}"
      state: directory
  - name: Unarchive the runtime
    unarchive:
      src: "{{ dotnet_path }}"
      dest: "{{ dotnet_target_path }}"
      creates: "{{ dotnet_target_path }}/dotnet"
  - name: Add Dotnet to path
    copy:
      dest: "{{ dotnet_sh_path }}"
      content: "[ -z \"$DOTNET_ROOT\" ] && export DOTNET_ROOT={{ dotnet_target_path }}"
  - name: Source the file to update $PATH
    shell: ". {{ dotnet_sh_path }}"
  - name: Create a Ghosts service file
    copy:
      dest: "/etc/systemd/system/ghosts.service"
      content: |
        [Unit]
        Description=GHOSTS Client Service
        After=network.target

        [Service]
        ExecStart={{ dotnet_target_path }}/dotnet {{ client_target_path }}/ghosts.client.linux.dll
        WorkingDirectory={{ client_target_path }}
        Restart=always
        User=ghosts_user
        Group=ghosts_user
        Environment=DOTNET_CLI_TELEMETRY_OPTOUT=1
        Environment=DISPLAY=:0

        [Install]
        WantedBy=multi-user.target
  - name: Enable the Ghosts client service
    systemd_service:
      name: ghosts
      state: started
      enabled: true





